### ISSUE TITLE
getTopClips error

### ISSUE THREAD

**Issue by sogehige** [sogebot/sogeBot#4957]
sogebot_1  | 2022-01-26T22:02:11.279 !!! ERROR !!! undefined => Error: Cannot initialize Twitch API, bot token invalid.
sogebot_1  |     at client (/app/src/services/twitch/api/client.ts:32:11)
sogebot_1  |     at getTopClips (/app/src/services/twitch/calls/getTopClips.ts:24:35)
sogebot_1  |     at Object.callback (/app/src/overlays/clipscarousel.ts:11:38)
sogebot_1  |     at Socket.<anonymous> (/app/src/socket.ts:81:22)
sogebot_1  |     at Socket.emit (node:events:390:28)
sogebot_1  |     at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
sogebot_1  |     at /app/node_modules/socket.io/dist/socket.js:466:39
sogebot_1  |     at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by sogehige** [comment]
This should trigger refresh token

**Comment by sogehige** [comment]
Also we should probably get rid of  undefined  as we have proper stack trace and use some generic error handler
