### ISSUE TITLE
The music doesn't work, it gives an error

### ISSUE THREAD

**Issue by Drahonn** [sogebot/sogeBot#5634]
### Expected behavior
Playing music
### Actual behavior
The music doesn't play and complete silence
### Steps to reproduce
Add track from yt in chat
### Additional informations

And this is being spammed in a HUGE AMOUNT in the console when i press PLAY button:

2023-01-24T07:12:02.094 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> Error: You must provide selection conditions in order to find a single row.
      at EntityManager.findOne (/home/bot/src/entity-manager/EntityManager.ts:1114:19)
      at Repository.findOne (/home/bot/src/repository/Repository.ts:536:29)
      at Function.findOne (/home/bot/src/repository/BaseEntity.ts:479:40)
      at Songs.sendNextSongID (/home/bot/src/systems/songs.ts:429:36)
      at Object.callback (/home/bot/src/systems/songs.ts:278:12)
      at Socket.<anonymous> (/home/bot/src/socket.ts:62:27)
      at Socket.emit (node:events:513:28)
      at Socket.emitUntyped (/home/bot/node_modules/socket.io/dist/typed-events.js:69:22)
      at /home/bot/node_modules/socket.io/dist/socket.js:614:39
      at processTicksAndRejections (node:internal/process/task_queues:78:11)
} reason: Error: You must provide selection conditions in order to find a single row.

**Comment by Drahonn** [comment]
And if it doesn't bother you to answer, then I would like to know how to edit the "public" page of the site? Where is the code from this page stored? Thank you in advance!

**Comment by sogehige** [comment]
you can see public page here https://github.com/sogebot/sogebot.dev/tree/main/ui.public
